laravel/app/routes.php
<?php

// Route::get('fix', function(){
// 	$clientes = \Clientes::all();
// 	foreach ($clientes as $key => $cliente) {
// 		$img = \Thumb::makeIconeClientesFile(public_path('assets/images/clientes/originais/'), $cliente->imagem, 120, 80, public_path('assets/images/clientes/home/'), 'rgba(0,0,0,0)', false);
// 		$cliente->icone = $img ? $img : '';
// 		$cliente->save();
// 	}
// });

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('projetos/{tipo_slug?}', array('as' => 'projetos', 'uses' => 'ProjetosController@index'));
Route::get('projetos/detalhes/{slug_cliente?}/{slug?}', array('as' => 'projetos.detalhes', 'uses' => 'ProjetosController@detalhes'));
Route::get('projetos/apresentacao/{slug?}', array('as' => 'projetos.detalhes', 'uses' => 'ProjetosController@apresentacao'));
Route::get('areas-de-atuacao/{area_slug?}', array('as' => 'atuacao', 'uses' => 'AtuacaoController@index'));
Route::get('areas-de-atuacao/{area_slug?}/{servico_slug?}', array('as' => 'atuacao.detalhes', 'uses' => 'AtuacaoController@detalhes'));
Route::get('trabalhe-conosco', array('as' => 'trabalheconosco', 'uses' => 'TrabalheConoscoController@index'));
Route::post('trabalhe-conosco', array('as' => 'trabalheconosco.enviar', 'uses' => 'TrabalheConoscoController@enviar'));
Route::post('trabalhe-conosco/upload', array('as' => 'trabalheconosco.upload', 'uses' => 'TrabalheConoscoController@upload'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('contato', array('as' => 'contato.enviar', 'uses' => 'ContatoController@enviar'));
Route::get('conheca-a-trupe/{area?}', array('as' => 'conheca', 'uses' => 'ConhecaController@index'));
Route::get('criacao-de-sites', array('as' => 'criacaodesites', 'uses' => 'CriacaoDeSitesController@index'));
Route::get('comunicacao-e-design', array('as' => 'comunicacaoedesign', 'uses' => 'ComunicacaoController@index'));
Route::get('branding', array('as' => 'branding', 'uses' => 'BrandingController@index'));
Route::get('novidades/{slug?}', array('as' => 'novidades', 'uses' => 'NovidadesController@index'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
	Route::any('multi-upload', 	array('as' => 'painel.portfolioimagens.upload', 'uses' => 'Painel\AjaxController@upload'));
	Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('clientes', 'Painel\ClientesController');
	Route::resource('trabalhos', 'Painel\TrabalhoController');
	Route::resource('tipostrabalho', 'Painel\TiposTrabalhoController');
	Route::resource('itenstrabalho', 'Painel\ItensTrabalhoController');
	Route::resource('apresentacao', 'Painel\ApresentacaoController');
	Route::resource('atuacao', 'Painel\AtuacaoController');
	Route::resource('servicos', 'Painel\ServicosController');
Route::resource('banners', 'Painel\BannersController');
Route::resource('chamadasclientes', 'Painel\ChamadasClientesController');
Route::resource('novidades', 'Painel\NovidadesController');
//NOVASROTASDOPAINEL//
});

laravel/app/models/ItensTrabalho.php
<?php

class ItensTrabalho extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'itens';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

    public function scopeOrdenado($query)
    {
    	return $query->orderBy('ordem', 'asc');
    }

    public function scopeSlug($query, $slug)
    {
    	return $query->where('slug', '=', $slug);
    }

    public function scopeNotThis($query, $id)
    {
    	return $query->where('id', '!=', $id);
    }

    public function trabalhos()
    {
        return $this->belongsToMany('Trabalho', 'item_trabalho', 'trabalho_id', 'itens_id');
    }

    public function apresentacao()
    {
        return $this->belongsToMany('Apresentacao', 'apresentacao_item', 'apresentacao_id', 'itens_id');
    }    
}

laravel/app/controllers/painel/ItensTrabalhoController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \Thumb, \Tools, \File, ItensTrabalho;

class ItensTrabalhoController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.itenstrabalho.index')->with('registros', ItensTrabalho::ordenado()->paginate(25));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.itenstrabalho.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new ItensTrabalho;

		$object->titulo = Input::get('titulo');
		$object->slug = Str::slug(Input::get('titulo'));

		if(sizeof(ItensTrabalho::slug($object->slug)->get()) > 0){
			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array("Já existe um cadastro para '<strong>{$object->titulo}</strong>'"));	
		}

		$icone = Thumb::make('icone', null, null, 'itenstrabalho/');
		if($icone){
			if(!Thumb::checkSize('icone', 25, 25)){
				Session::flash('formulario', Input::except('icone'));
				return Redirect::back()->withErrors(array("O tamanho máximo para o ícone é '<strong>25px x 25px</strong>'"));	
			}
			$object->icone = $icone;	
		}

		try {

			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Item criado com sucesso.');
			return Redirect::route('painel.itenstrabalho.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Item!'));	

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.itenstrabalho.edit')->with('registro', ItensTrabalho::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = ItensTrabalho::find($id);

		$object->titulo = Input::get('titulo');
		$object->slug = Str::slug(Input::get('titulo'));

		if(sizeof(ItensTrabalho::slug($object->slug)->notThis($object->id)->get()) > 0){
			return Redirect::back()->withErrors(array("Já existe um cadastro para '<strong>{$object->titulo}</strong>'"));	
		}

		$icone = Thumb::make('icone', null, null, 'itenstrabalho/');
		if($icone){
			if(!Thumb::checkSize('icone', 25, 25)){
				Session::flash('formulario', Input::except('icone'));
				return Redirect::back()->withErrors(array("O tamanho máximo para o ícone é '<strong>25px x 25px</strong>'"));	
			}
			$object->icone = $icone;	
		}

		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Item alterado com sucesso.');
			return Redirect::route('painel.itenstrabalho.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Item!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = ItensTrabalho::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Item removido com sucesso.');

		return Redirect::route('painel.itenstrabalho.index');
	}

}

laravel/app/views/backend/itenstrabalho/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Item
        </h2>  

		{{ Form::open( array('route' => array('painel.itenstrabalho.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	


				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" value="{{$registro->titulo}}" required>
				</div>
					
				<div class="well">
					<div class="form-group">
						@if($registro->icone)
							<h4>Ícone Atual</h4>
							<div class="circulo-pequeno-hover">
								<img src="assets/images/itenstrabalho/{{$registro->icone}}">
							</div>
							<p class="alert alert-warning" style="margin-top:10px;"><em>passe o cursor sobre a imagem para ativar o fundo de contraste</em></p>
						@endif
						<hr>
						<label for="inputÍcone">Trocar Ícone</label>
						<p>
							<em>
								PNG com fundo transparente<br>
								tamanho máximo : 25px x 25px
							</em>
						</p>
						<input type="file" class="form-control" id="inputÍcone" name="icone">
					</div>
				</div>
				

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.itenstrabalho.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/itenstrabalho/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Item
        </h2>  

		<form action="{{URL::route('painel.itenstrabalho.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif


				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" @if(Session::has('formulario')) value="{{ Session::get('formulario.titulo') }}" @endif required>
				</div>
				
				<div class="well">
					<div class="form-group">
						<label for="inputÍcone">Ícone </label>
						<p>
							<em>
								PNG com fundo transparente<br>
								tamanho máximo : 25px x 25px
							</em>
						</p>
						<input type="file" class="form-control" id="inputÍcone" name="icone" required>
					</div>
				</div>
				

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.itenstrabalho.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/itenstrabalho/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Itens dos Trabalhos <a href='{{ URL::route('painel.itenstrabalho.create') }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Item</a>
    </h2>

    <table class='table table-striped table-bordered table-hover table-sortable' data-tabela='itens'>

        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Título</th>
				<th>Ícone</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td class='move-actions'><a href='#' class='btn btn-info btn-move btn-sm'>mover</a></td>
                <td>{{ $registro->titulo }}</td>
				<td style="background:#065562;">
                    <div class="circulo-pequeno">
                        <img src='assets/images/itenstrabalho/{{ $registro->icone }}'>
                    </div>
                </td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.itenstrabalho.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
					{{ Form::open(array('route' => array('painel.itenstrabalho.destroy', $registro->id), 'method' => 'delete')) }}
						<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
					{{ Form::close() }}                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    {{ $registros->links() }}
</div>

@stop