laravel/app/routes.php
<?php

// Route::get('fix', function(){
// 	$clientes = \Clientes::all();
// 	foreach ($clientes as $key => $cliente) {
// 		$img = \Thumb::makeIconeClientesFile(public_path('assets/images/clientes/originais/'), $cliente->imagem, 120, 80, public_path('assets/images/clientes/home/'), 'rgba(0,0,0,0)', false);
// 		$cliente->icone = $img ? $img : '';
// 		$cliente->save();
// 	}
// });

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('projetos/{tipo_slug?}', array('as' => 'projetos', 'uses' => 'ProjetosController@index'));
Route::get('projetos/detalhes/{slug_cliente?}/{slug?}', array('as' => 'projetos.detalhes', 'uses' => 'ProjetosController@detalhes'));
Route::get('projetos/apresentacao/{slug?}', array('as' => 'projetos.detalhes', 'uses' => 'ProjetosController@apresentacao'));
Route::get('areas-de-atuacao/{area_slug?}', array('as' => 'atuacao', 'uses' => 'AtuacaoController@index'));
Route::get('areas-de-atuacao/{area_slug?}/{servico_slug?}', array('as' => 'atuacao.detalhes', 'uses' => 'AtuacaoController@detalhes'));
Route::get('trabalhe-conosco', array('as' => 'trabalheconosco', 'uses' => 'TrabalheConoscoController@index'));
Route::post('trabalhe-conosco', array('as' => 'trabalheconosco.enviar', 'uses' => 'TrabalheConoscoController@enviar'));
Route::post('trabalhe-conosco/upload', array('as' => 'trabalheconosco.upload', 'uses' => 'TrabalheConoscoController@upload'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('contato', array('as' => 'contato.enviar', 'uses' => 'ContatoController@enviar'));
Route::get('conheca-a-trupe/{area?}', array('as' => 'conheca', 'uses' => 'ConhecaController@index'));
Route::get('criacao-de-sites', array('as' => 'criacaodesites', 'uses' => 'CriacaoDeSitesController@index'));
Route::get('comunicacao-e-design', array('as' => 'comunicacaoedesign', 'uses' => 'ComunicacaoController@index'));
Route::get('branding', array('as' => 'branding', 'uses' => 'BrandingController@index'));
Route::get('novidades/{slug?}', array('as' => 'novidades', 'uses' => 'NovidadesController@index'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
	Route::any('multi-upload', 	array('as' => 'painel.portfolioimagens.upload', 'uses' => 'Painel\AjaxController@upload'));
	Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('clientes', 'Painel\ClientesController');
	Route::resource('trabalhos', 'Painel\TrabalhoController');
	Route::resource('tipostrabalho', 'Painel\TiposTrabalhoController');
	Route::resource('itenstrabalho', 'Painel\ItensTrabalhoController');
	Route::resource('apresentacao', 'Painel\ApresentacaoController');
	Route::resource('atuacao', 'Painel\AtuacaoController');
	Route::resource('servicos', 'Painel\ServicosController');
Route::resource('banners', 'Painel\BannersController');
Route::resource('chamadasclientes', 'Painel\ChamadasClientesController');
Route::resource('novidades', 'Painel\NovidadesController');
//NOVASROTASDOPAINEL//
});

laravel/app/models/Trabalho.php
<?php

class Trabalho extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'trabalhos';
    

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');
    
    public function scopeOrdenado($query)
    {
        return $query->orderBy('ordem', 'asc');
    }
    
    public function scopeSlug($query, $slug)
    {
        return $query->where('slug', '=', $slug);
    }

    public function scopeNotThis($query, $id)
    {
        return $query->where('id', '!=', $id);
    }
    
    public function cliente()
    {
        return $this->belongsTo('Clientes', 'clientes_id');
    }

    public function tipos()
    {
        return $this->belongsToMany('TiposTrabalho', 'tipo_trabalho', 'trabalho_id', 'tipo_id')
                    ->orderBy('titulo', 'asc');
    }

    public function itens()
    {
        return $this->belongsToMany('ItensTrabalho', 'item_trabalho', 'itens_id', 'trabalho_id')
                    ->orderBy('ordem', 'asc');
    }

    public function imagens()
    {
        return $this->hasMany('TrabalhoImagens', 'trabalhos_id')->ordenado();
    }

}

laravel/app/controllers/painel/TrabalhoController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \Thumb, \Tools, \File, \Trabalho, \Clientes, \TiposTrabalho, \ItensTrabalho, \TrabalhoImagens;

class TrabalhoController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		if(Input::has('clientes_id')){
			$cliente = Clientes::with('trabalhos')->find(Input::get('clientes_id'));
			$registros = $cliente->trabalhos()->paginate(25);
		}else{ 
			$cliente = null;
			$registros = Trabalho::with('tipos')->ordenado()->paginate(2500);
		}
		
		$listaClientes = Clientes::ordenado()->get();
		$listaTipos = TiposTrabalho::ordenado()->get();
		$listaItens = ItensTrabalho::ordenado()->get();

		$this->layout->content = View::make('backend.trabalhos.index')->with(compact('registros'))
																	  ->with(compact('listaClientes'))
																	  ->with(compact('listaTipos'))
																	  ->with(compact('listaItens'))
																	  ->with(compact('cliente'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$listaClientes = Clientes::ordenado()->get();
		$listaTipos = TiposTrabalho::ordenado()->get();
		$listaItens = ItensTrabalho::ordenado()->get();

		$clientes_id = Input::has('clientes_id') ? Input::get('clientes_id') : null;

		$this->layout->content = View::make('backend.trabalhos.form')->with(compact('listaClientes'))
																	 ->with(compact('listaTipos'))
																	 ->with(compact('listaItens'))
																	 ->with(compact('clientes_id'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Trabalho;

		$object->clientes_id = Input::get('clientes_id');
		
		$capa = Thumb::make('capa', 650, 405, 'projetos/capas/', false, '#065562', false);
		if($capa) $object->capa = $capa;

		$thumb = Thumb::make('thumb', 200, 200, 'projetos/capas_redondas/');
		if($thumb) $object->thumb = $thumb;
		
		$object->titulo = Input::get('titulo');
		$object->olho = Input::get('olho');
		$object->texto = Input::get('texto');
		$object->link = Input::get('link');
		$object->reel = Input::get('reel');

		$itens = Input::has('itens') ? Input::get('itens') : array();
		$tipos = Input::has('tipos') ? Input::get('tipos') : array();

		$object->ordem = -1;
		
		try {

			$object->save();

			$object->slug = $this->geraSlug($object->id);
			$object->save();

			$object->itens()->sync($itens);
			$object->tipos()->sync($tipos);

			// Salvar imagens do trabalho
			$imagens = Input::get('imagem');
			$descricoes = Input::get('descricao');

			if($imagens && is_array($imagens)){
				foreach ($imagens as $key => $value) {
					$obj = new TrabalhoImagens;
					$obj->trabalhos_id = $object->id;
					$obj->imagem = $value;
					$obj->ordem = $key;
					$obj->descricao = isset($descricoes[$key]) ? $descricoes[$key] : '';
					$obj->save();
				}
			}

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Trabalho criado com sucesso.');
			return Redirect::route('painel.trabalhos.index', array('clientes_id' => $object->clientes_id));

		} catch (\Exception $e) {

			Session::flash('formulario', Input::except(array('capa', 'thumb')));
			return Redirect::back()->withErrors(array('Erro ao criar Trabalho! <br>'.$e->getMessage()));

		}
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$registro = Trabalho::with('tipos', 'itens', 'cliente')->find($id);
		$listaClientes = Clientes::ordenado()->get();
		$listaTipos = TiposTrabalho::ordenado()->get();
		$listaItens = ItensTrabalho::ordenado()->get();

		$lista_ids_tipos_relacionados = $registro->tipos->lists('id');
		$lista_ids_itens_relacionados = $registro->itens->lists('id');
		$this->layout->content = View::make('backend.trabalhos.edit')->with(compact('registro'))
																	 ->with(compact('listaClientes'))
																	 ->with(compact('listaTipos'))
																	 ->with(compact('listaItens'))
																	 ->with(compact('lista_ids_tipos_relacionados'))
																	 ->with(compact('lista_ids_itens_relacionados'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Trabalho::find($id);

		$object->clientes_id = Input::get('clientes_id');
		
		$capa = Thumb::make('capa', 650, 405, 'projetos/capas/', false, '#065562', false);
		if($capa) $object->capa = $capa;

		$thumb = Thumb::make('thumb', 200, 200, 'projetos/capas_redondas/');
		if($thumb) $object->thumb = $thumb;

		$object->titulo = Input::get('titulo');
		$object->slug = $this->geraSlug($object->id);
		$object->olho = Input::get('olho');
		$object->texto = Input::get('texto');
		$object->link = Input::get('link');
		$object->reel = Input::get('reel');

		$itens = Input::has('itens') ? Input::get('itens') : array();
		$tipos = Input::has('tipos') ? Input::get('tipos') : array();

		try {

			$object->save();

			$object->itens()->sync($itens);
			$object->tipos()->sync($tipos);

			TrabalhoImagens::where('trabalhos_id', '=', $object->id)->delete();
			
			$imagens = Input::get('imagem');
			$descricoes = Input::get('descricao');

			if($imagens && is_array($imagens)){
				foreach ($imagens as $key => $value) {
					$obj = new TrabalhoImagens;
					$obj->trabalhos_id = $object->id;
					$obj->imagem = $value;
					$obj->ordem = $key;
					$obj->descricao = isset($descricoes[$key]) ? $descricoes[$key] : '';
					$obj->save();
				}
			}

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Trabalho alterado com sucesso.');
			return Redirect::route('painel.trabalhos.index', array('clientes_id' => $object->clientes_id));

		} catch (\Exception $e) {

			Session::flash('formulario', Input::except(array('capa', 'thumb')));
			return Redirect::back()->withErrors(array('Erro ao criar Trabalho!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Trabalho::find($id);
		$clientes_id = $object->clientes_id;
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Trabalho removido com sucesso.');

		return Redirect::route('painel.trabalhos.index', array('clientes_id' => $clientes_id));
	}

	/**
	 * Method from creating a unique slug for the project
	 * The url is composed by the client slug + project slug
	 * Examples : projetos/detalhes/meta-executivos/e-mail-marketing
	 *			  projetos/detalhes/meta-bpo/e-mail-marketing
	 *
	 * If we have the same project title whithin the same client
	 * we should append a incrementing integer
	 * Examples : projetos/detalhes/meta-executivos/e-mail-marketing
	 *			  projetos/detalhes/meta-executivos/e-mail-marketing-1
	 *			  projetos/detalhes/meta-executivos/e-mail-marketing-2
	 * And so on...
	 *
	 * @return String
	 */
	public function geraSlug($trabalho_atual_id)
	{
		$cliente_id 	= Input::get('clientes_id');
		$titulo  		= Input::get('titulo');
		$slug 			= Str::slug($titulo);
		$slug_check		= '';
		$append_digito 	= 1;
		$append_string  = '-';

		// Check for matching project slug and client id
		$query = Trabalho::whereHas('cliente', function($q) use ($cliente_id){
			$q->where('id', '=', $cliente_id);
		})->slug($slug)->notThis($trabalho_atual_id)->get();

		if(sizeof($query) == 0){
			// If there's no matching slugs for the same client,
			// just return the Slugified Title
			return $slug;
		}else{
			// While the current slug exists, do
			while(sizeof($query) > 0){
				
				// Append the digit to the current slug
				$slug_check = $slug . $append_string . $append_digito;
				
				// Check again
				$query = Trabalho::whereHas('cliente', function($q) use ($cliente_id){
					$q->where('id', '=', $cliente_id);
				})->slug($slug_check)->notThis($trabalho_atual_id)->get();

				// Increment the digit for the next iterarion
				$append_digito++;
			}
			// Return appended slug
			return $slug_check;
		}
	}
}

laravel/app/views/backend/trabalhos/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
      		@if(isset($clientes_id) && !is_null($clientes_id))
      			Cliente: <span class="text-primary">{{ Clientes::find($clientes_id)->titulo }}</span>
        		<span class="subdir1">Adicionar Trabalho</span>
        	@else
        		Adicionar Trabalho
      		@endif
        </h2>  

	    <hr>
	    <a href="{{ URL::route('painel.trabalhos.index', array('clientes_id' => $clientes_id)) }}" class="btn btn-sm btn-default">&larr; voltar para Trabalhos</a>
	    <hr>

		<form action="{{URL::route('painel.trabalhos.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif


				<div class="form-group">
					<label for="inputCliente">Cliente</label>					 
					<select	name="clientes_id" class="form-control" id="inputCliente" required>
						<option value="">Selecione</option>
						@if(sizeof($listaClientes) > 0)
							@foreach ($listaClientes as $cliente)
								<option value="{{ $cliente->id }}" @if((Session::has('formulario') && Session::get('formulario.clientes_id') == $cliente->id) || (isset($clientes_id) && !is_null($clientes_id) && $clientes_id == $cliente->id)) selected @endif>{{ $cliente->titulo }}</option>
							@endforeach
						@endif
					</select>
				</div>

			</div>


			<hr>
			<div class="well">
				<h4>Tipo de Trabalho</h4>
				<hr>
				@if(sizeof($listaTipos) > 0)
					<div class="itensbox container-fluid">
						<div class="row">
							@foreach ($listaTipos as $i => $tipo)
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label class="checkbox-inline" style="margin-bottom:3px;"><input type="checkbox" name="tipos[]" value="{{ $tipo->id }}" @if(Session::has('formulario') && is_array(Session::get('formulario.tipos')) && in_array($tipo->id, Session::get('formulario.tipos'))) checked @endif > {{ $tipo->titulo }}</label>
								</div>
								@if(($i + 1)%3 == 0)
									</div><div class="row">
								@endif
							@endforeach
						</div>
					</div>
				@else
					<h5>- Nenhum tipo cadastrado</h5>
				@endif
			</div>
			<hr>
				
			<div class="pad">

				<div class="form-group">
					<label for="inputCapa">Capa para página de detalhes (730x340)</label>
					<input type="file" class="form-control" id="inputCapa" name="capa" required>
				</div>

				<hr>

				<div class="form-group">
					<label for="inputThumb">Capa para listagem (200x200)</label>
					<input type="file" class="form-control" id="inputThumb" name="thumb" required>
				</div>

				<hr>
				
				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<br>
					<small>Quebra de linha : &lt;br&gt;</small>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" @if(Session::has('formulario')) value="{{ Session::get('formulario.titulo') }}" @endif required>
				</div>
				
				<div class="form-group">
					<label for="inputOlho">Olho</label>
					<input type="text" class="form-control" id="inputOlho" name="olho" @if(Session::has('formulario')) value="{{ Session::get('formulario.olho') }}" @endif>
				</div>
				
				<div class="form-group">
					<label for="inputTexto">Texto</label>
					<textarea name="texto" class="form-control" id="inputTexto" >@if(Session::has('formulario')) {{ Session::get('formulario.texto') }} @endif</textarea>
				</div>
				
				<div class="form-group">
					<label for="inputLink">Link para versão que está no ar</label>
					<input type="text" class="form-control" id="inputLink" name="link" @if(Session::has('formulario')) value="{{ Session::get('formulario.link') }}" @endif >
				</div>
				
				<div class="form-group">
					<label for="inputReel">Reel (URL do Vimeo)</label>
					<input type="text" class="form-control" id="inputReel" name="reel" @if(Session::has('formulario')) value="{{ Session::get('formulario.reel') }}" @endif >
				</div>

			</div>
			
			<hr>

			<div class="well">
				<h4>Itens desenvolvidos no Trabalho</h4>
				<hr>
				@if(sizeof($listaItens) > 0)
					<div class="itensbox container-fluid">
						<div class="row">
							@foreach ($listaItens as $k => $item)
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label class="checkbox-inline" style="margin-bottom:3px;"><input type="checkbox" name="itens[]" value="{{ $item->id }}" @if(Session::has('formulario') && is_array(Session::get('formulario.itens')) && in_array($item->id, Session::get('formulario.itens'))) checked @endif > {{ $item->titulo }}</label>
								</div>
								@if(($k + 1)%3 == 0)
									</div><div class="row">
								@endif
							@endforeach
						</div>
					</div>
				@else
					<h5>- Nenhum item cadastrado</h5>
				@endif
			</div>
				
			<div class="well">
				<label>Imagens</label>
				
				<div id="multiUpload">
					<div id="icone">
						<span class="glyphicon glyphicon-open"></span>
						<span class="glyphicon glyphicon-refresh"></span>
					</div>
					<p>
						Escolha as imagens do Projeto. Você pode selecionar mais de um arquivo ao mesmo tempo. Você também pode arrastar e soltar arquivos nesta área para começar a enviar.<br>
						Se preferir também pode utilizar o botão abaixo para selecioná-las.
					</p>
					<input id="fileupload" type="file" name="files[]" data-url="painel/multi-upload" multiple>					
				</div>
				<div id="listaImagens"></div>
				<div class="panel panel-default">
					<div class="panel-body">
				    	Você pode clicar e arrastar as imagens para ordená-las.
				  	</div>
				</div>
			</div>

			<hr>

			<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

			<a href="{{URL::route('painel.trabalhos.index', array('clientes_id' => $clientes_id))}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

		</form>
    </div>
    
@stop

laravel/app/views/backend/trabalhos/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Cliente: <span class="text-primary">{{ $cliente->titulo or "Todos os Clientes" }}</span> <a href='{{ URL::route('painel.trabalhos.create', array('clientes_id' => isset($cliente->id) ? $cliente->id : '' )) }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Trabalho</a><br>
        <span class="subdir1">Trabalhos</span>
    </h2>
    
    @if(isset($cliente->titulo))
    <hr>
    <a href="{{ URL::route('painel.clientes.index') }}" class="btn btn-sm btn-default">&larr; voltar para Clientes</a>
    <hr>
    @endif
    
    <table class='table table-striped table-bordered table-hover table-sortable' data-tabela='trabalhos'>

        <thead>
            <tr>
                @if(!isset($cliente->titulo))
                    <th>Ordenar</th>
                @endif
                <th>Tipo de Trabalho</th>
				<th>Capa</th>
				<th>Título</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                @if(!isset($cliente->titulo))
                    <td class='move-actions'><a href='#' class='btn btn-info btn-move btn-sm'>mover</a></td>
                @endif
                <td>
                    @if(sizeof($registro->tipos))
                        <ul>
                        @foreach($registro->tipos as $tipo)
                            <li>&middot; {{ $tipo->titulo }}</li>
                        @endforeach
                        </ul>
                    @else
                        Não Encontrado
                    @endif
                </td>
				<td><img src='assets/images/projetos/capas/{{ $registro->capa }}' style='max-width:150px'></td>
				<td>{{ strip_tags($registro->titulo) }}</td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.trabalhos.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
					{{ Form::open(array('route' => array('painel.trabalhos.destroy', $registro->id), 'method' => 'delete')) }}
						<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
					{{ Form::close() }}                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    {{ $registros->links() }}
</div>

@stop