laravel/app/routes.php
<?php

// Route::get('fix', function(){
// 	$clientes = \Clientes::all();
// 	foreach ($clientes as $key => $cliente) {
// 		$img = \Thumb::makeIconeClientesFile(public_path('assets/images/clientes/originais/'), $cliente->imagem, 120, 80, public_path('assets/images/clientes/home/'), 'rgba(0,0,0,0)', false);
// 		$cliente->icone = $img ? $img : '';
// 		$cliente->save();
// 	}
// });

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('projetos/{tipo_slug?}', array('as' => 'projetos', 'uses' => 'ProjetosController@index'));
Route::get('projetos/detalhes/{slug_cliente?}/{slug?}', array('as' => 'projetos.detalhes', 'uses' => 'ProjetosController@detalhes'));
Route::get('projetos/apresentacao/{slug?}', array('as' => 'projetos.detalhes', 'uses' => 'ProjetosController@apresentacao'));
Route::get('areas-de-atuacao/{area_slug?}', array('as' => 'atuacao', 'uses' => 'AtuacaoController@index'));
Route::get('areas-de-atuacao/{area_slug?}/{servico_slug?}', array('as' => 'atuacao.detalhes', 'uses' => 'AtuacaoController@detalhes'));
Route::get('trabalhe-conosco', array('as' => 'trabalheconosco', 'uses' => 'TrabalheConoscoController@index'));
Route::post('trabalhe-conosco', array('as' => 'trabalheconosco.enviar', 'uses' => 'TrabalheConoscoController@enviar'));
Route::post('trabalhe-conosco/upload', array('as' => 'trabalheconosco.upload', 'uses' => 'TrabalheConoscoController@upload'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('contato', array('as' => 'contato.enviar', 'uses' => 'ContatoController@enviar'));
Route::get('conheca-a-trupe/{area?}', array('as' => 'conheca', 'uses' => 'ConhecaController@index'));
Route::get('criacao-de-sites', array('as' => 'criacaodesites', 'uses' => 'CriacaoDeSitesController@index'));
Route::get('comunicacao-e-design', array('as' => 'comunicacaoedesign', 'uses' => 'ComunicacaoController@index'));
Route::get('branding', array('as' => 'branding', 'uses' => 'BrandingController@index'));
Route::get('novidades/{slug?}', array('as' => 'novidades', 'uses' => 'NovidadesController@index'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
	Route::any('multi-upload', 	array('as' => 'painel.portfolioimagens.upload', 'uses' => 'Painel\AjaxController@upload'));
	Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('clientes', 'Painel\ClientesController');
	Route::resource('trabalhos', 'Painel\TrabalhoController');
	Route::resource('tipostrabalho', 'Painel\TiposTrabalhoController');
	Route::resource('itenstrabalho', 'Painel\ItensTrabalhoController');
	Route::resource('apresentacao', 'Painel\ApresentacaoController');
	Route::resource('atuacao', 'Painel\AtuacaoController');
	Route::resource('servicos', 'Painel\ServicosController');
Route::resource('banners', 'Painel\BannersController');
Route::resource('chamadasclientes', 'Painel\ChamadasClientesController');
Route::resource('novidades', 'Painel\NovidadesController');
//NOVASROTASDOPAINEL//
});

laravel/app/models/Novidades.php
<?php

class Novidades extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'novidades';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

    public function scopeOrdenado($query)
    {
        return $query->orderBy('id', 'desc');
    }
    public function scopeSlug($query, $slug)
    {
        return $query->where('slug', '=', $slug);
    }
    public function scopeNotThis($query, $id)
    {
        return $query->where('id', '!=', $id);
    }
}

laravel/app/controllers/NovidadesController.php
<?php

use \Novidades;

class NovidadesController extends BaseController{
	
	protected $layout = 'frontend.templates.index';

	public function index($slug = '')
	{
		if(!$slug){
			$detalhe = \Novidades::ordenado()->first();
		}else{
			$detalhe = \Novidades::slug($slug)->first();
		}

		if(is_null($detalhe)) App::abort('404');
		
		$listaNovidades = \Novidades::ordenado()->get();

		$view = View::make('frontend.novidades.index')->with(compact('detalhe'))
													  ->with(compact('listaNovidades'));

		if(Request::ajax()){
			$sections = $view->renderSections();
	        return $sections['conteudo'];
		}
		else
			$this->layout->content = $view;		
	}

}

laravel/app/controllers/painel/NovidadesController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \Thumb, \Tools, \File, Novidades;

class NovidadesController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.novidades.index')->with('registros', Novidades::ordenado()->paginate(25));		
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.novidades.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Novidades;

		$object->titulo = Input::get('titulo');
		$object->chamada = Input::get('chamada');
		$object->texto = Input::get('texto');

		$imagem = Thumb::make('imagem', 500, null, 'novidades/', false, 'rgba(0, 0, 0, 0)');
		if($imagem) $object->imagem = $imagem;

		
		try {

			$object->save();

			$object->slug = $this->geraSlug($object->id);
			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Novidade criado com sucesso.');
			return Redirect::route('painel.novidades.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Novidade!'));	

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.novidades.edit')->with('registro', Novidades::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Novidades::find($id);

		$object->titulo = Input::get('titulo');
		$object->slug = $this->geraSlug($object->id);
		$object->chamada = Input::get('chamada');
		$object->texto = Input::get('texto');

		$imagem = Thumb::make('imagem', 500, null, 'novidades/', false, 'rgba(0, 0, 0, 0)');
		if($imagem) $object->imagem = $imagem;

		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Novidade alterado com sucesso.');
			return Redirect::route('painel.novidades.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Novidade!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Novidades::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Novidade removido com sucesso.');

		return Redirect::route('painel.novidades.index');
	}

	/**
	 * Method from creating a unique slug for the news
	 *
	 * @return String
	 */
	public function geraSlug($novidade_atual_id)
	{
		$titulo  		= Input::get('titulo');
		$slug 			= Str::slug($titulo);
		$slug_check		= '';
		$append_digito 	= 1;
		$append_string  = '-';

		$query = Novidades::slug($slug)->notThis($novidade_atual_id)->get();

		if(sizeof($query) == 0){
			return $slug;
		}else{
			while(sizeof($query) > 0){
				
				$slug_check = $slug . $append_string . $append_digito;
				
				$query = Novidades::slug($slug_check)->notThis($novidade_atual_id)->get();

				$append_digito++;
			}
			return $slug_check;
		}
	}
}

laravel/app/views/backend/novidades/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Novidade
        </h2>  

		{{ Form::open( array('route' => array('painel.novidades.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	


				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" value="{{$registro->titulo}}" required>
				</div>

				<div class="form-group">
					<label for="inputChamadanaHome">Chamada na Home</label>
					<input type="text" class="form-control" id="inputChamadanaHome" name="chamada" value="{{$registro->chamada}}" required>
				</div>

				<div class="well">
					<div class="form-group">
						@if($registro->imagem)
							Imagem Atual<br>
							<img style="max-width:100%; margin:10px auto;" src="assets/images/novidades/{{$registro->imagem}}"><br>
						@endif
						<label for="inputImagem">Trocar Imagem</label>
						<input type="file" class="form-control" id="inputImagem" name="imagem">
					</div>
				</div>
				
				<div class="form-group">
					<label for="inputTexto">Texto</label>
					<textarea name="texto" class="form-control" id="inputTexto" >{{$registro->texto }}</textarea>
				</div>
				

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.novidades.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/novidades/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Novidade
        </h2>  

		<form action="{{URL::route('painel.novidades.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif


				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" @if(Session::has('formulario')) value="{{ Session::get('formulario.titulo') }}" @endif required>
				</div>
				
				<div class="form-group">
					<label for="inputChamada na Home">Chamada na Home</label>
					<input type="text" class="form-control" id="inputChamada na Home" name="chamada" @if(Session::has('formulario')) value="{{ Session::get('formulario.chamada') }}" @endif required>
				</div>

				<div class="well">
					<div class="form-group">
						<label for="inputImagem">Imagem</label>
						<input type="file" class="form-control" id="inputImagem" name="imagem" required>
					</div>
				</div>
				
				<div class="form-group">
					<label for="inputTexto">Texto</label>
					<textarea name="texto" class="form-control" id="inputTexto" >@if(Session::has('formulario')) {{ Session::get('formulario.texto') }} @endif</textarea>
				</div>
				

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.novidades.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/novidades/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Novidades <a href='{{ URL::route('painel.novidades.create') }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Novidade</a>
    </h2>

    <table class='table table-striped table-bordered table-hover'>

        <thead>
            <tr>
                <th>Título</th>
				<th>Chamada na Home</th>
				<th>Texto</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td>{{ $registro->titulo }}</td>
				<td>{{ $registro->chamada }}</td>
				<td>{{ Str::words(strip_tags($registro->texto), 15) }}</td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.novidades.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
						{{ Form::open(array('route' => array('painel.novidades.destroy', $registro->id), 'method' => 'delete')) }}
							<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
						{{ Form::close() }}                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    {{ $registros->links() }}
</div>

@stop